export enum ErrorCode {
  /// generic
  RUNTIME_ERROR = 500, // -> INTERNAL_SERVER_ERROR 500
  VALIDATION_FAILED = 501, // -> UNPROCESSABLE_ENTITY 422
  HTTP_EXCEPTION = 503, // -> error.status
  INVALID_REQUEST = 504, // -> BAD_REQUEST 400
  INVALID_OPERATION = 505, // -> UNPROCESSABLE_ENTITY 422
  MISSING_FEATURE = 510, // -> INTERNAL_SERVER_ERROR 500
  INVALID_RESPONSE = 511, // -> INTERNAL_SERVER_ERROR 500
  INVALID_ARGUMENT = 512, // -> BAD_REQUEST 400

  TIMEOUT = 600, // => GATEWAY_TIMEOUT
}