version: '3'

name: country-flag

networks:
  services:
    driver: bridge


services:
  postgres:
    image: "postgres:16-alpine"
    container_name: "postgresql"

    ports:
      - "5632:5432"

    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example

    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'

volumes:
  postgresql_data: